server:
  port: 8090

spring:
  application:
    name: provider-mock

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.training.providermock: INFO
